# Generated by Django 3.2.7 on 2021-11-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetailpage',
            name='blog_summary',
            field=models.TextField(default=False, help_text='Give a summary of the blog', max_length=400),
            preserve_default=False,
        ),
    ]
