# Generated by Django 3.2.7 on 2021-11-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogdetailpage_blog_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='blog_summary',
            field=models.TextField(blank=True, help_text='Give a summary of the blog', max_length=400, null=True),
        ),
    ]
